[package]
name = "nanai_veintiuna_rs"
version = "0.2.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.9"
rand = "0.9"
anyhow = "1.0"
clap = "4.5.45"
dialoguer = "0.11.0"
