[package]
name = "nanai_veintiuna_rs"
version = "0.2.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
toml = "0.*"
rand = "0.*"
anyhow = "1"
clap = "4"
dialoguer = "0.*"
